
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ARRAY ASTERISCO AVL BETWEEN BTREE CADENA COMMA CREATE DATE DELETE EQUAL FILE FLOAT FLOATVAL FROM HASH ID IN INDEX INSERT INT INTO ISAM KEY LBRACKET LPAREN NUM RBRACKET RPAREN RTREE SELECT SEQ TABLE TEXT USING VALUES VARCHAR WHEREprograma : sentenciasentencia : CREATE TABLE ID LPAREN def_columnas RPARENdef_columnas : columna\n                    | columna COMMA def_columnascolumna : ID tipo opciones_coltipo : INT\n            | VARCHAR LBRACKET NUM RBRACKET\n            | DATE\n            | ARRAY LBRACKET FLOAT RBRACKET\n            | TEXT\n            | FLOATopciones_col : \n                    | KEY \n                    | KEY INDEX tipo_indice\n                    | INDEX tipo_indicetipo_indice : SEQ \n                   | BTREE \n                   | RTREE\n                   | AVL\n                   | ISAM\n                   | HASHsentencia : CREATE TABLE ID FROM FILE CADENA USING INDEX ID LPAREN CADENA RPARENsentencia : SELECT columns FROM ID condicion_wherecolumns : ASTERISCO\n               | ID\n               | ID COMMA columnscondicion_where : \n                       | WHERE condicioncondicion : ID EQUAL valor\n                 | ID BETWEEN valor AND valor\n                 | ID IN LPAREN valor COMMA valor RPARENvalor : NUM\n             | FLOATVAL\n             | CADENAsentencia : INSERT INTO ID VALUES LPAREN valores RPARENvalores : valor\n               | valor COMMA valoressentencia : DELETE FROM ID WHERE condicion'
    
_lr_action_items = {'CREATE':([0,],[3,]),'SELECT':([0,],[4,]),'INSERT':([0,],[5,]),'DELETE':([0,],[6,]),'$end':([1,2,20,28,32,40,43,46,47,48,59,61,82,87,88,],[0,-1,-27,-23,-38,-2,-28,-32,-33,-34,-35,-29,-30,-31,-22,]),'TABLE':([3,],[7,]),'ASTERISCO':([4,15,],[10,10,]),'ID':([4,7,11,12,14,15,18,23,29,41,74,],[9,13,16,17,20,9,24,31,31,24,81,]),'INTO':([5,],[11,]),'FROM':([6,8,9,10,13,21,],[12,14,-25,-24,19,-26,]),'COMMA':([9,26,33,34,36,38,39,45,46,47,48,52,53,65,66,67,68,69,70,71,77,78,79,80,],[15,41,-12,-6,-8,-11,-10,60,-32,-33,-34,-5,-13,-15,-16,-17,-18,-19,-20,-21,83,-14,-7,-9,]),'LPAREN':([13,22,51,81,],[18,30,63,84,]),'VALUES':([16,],[22,]),'WHERE':([17,20,],[23,29,]),'FILE':([19,],[27,]),'INT':([24,],[34,]),'VARCHAR':([24,],[35,]),'DATE':([24,],[36,]),'ARRAY':([24,],[37,]),'TEXT':([24,],[39,]),'FLOAT':([24,56,],[38,73,]),'RPAREN':([25,26,33,34,36,38,39,44,45,46,47,48,52,53,57,65,66,67,68,69,70,71,75,78,79,80,85,86,],[40,-3,-12,-6,-8,-11,-10,59,-36,-32,-33,-34,-5,-13,-4,-15,-16,-17,-18,-19,-20,-21,-37,-14,-7,-9,87,88,]),'CADENA':([27,30,49,50,60,63,76,83,84,],[42,48,48,48,48,48,48,48,86,]),'NUM':([30,49,50,55,60,63,76,83,],[46,46,46,72,46,46,46,46,]),'FLOATVAL':([30,49,50,60,63,76,83,],[47,47,47,47,47,47,47,]),'EQUAL':([31,],[49,]),'BETWEEN':([31,],[50,]),'IN':([31,],[51,]),'KEY':([33,34,36,38,39,79,80,],[53,-6,-8,-11,-10,-7,-9,]),'INDEX':([33,34,36,38,39,53,58,79,80,],[54,-6,-8,-11,-10,64,74,-7,-9,]),'LBRACKET':([35,37,],[55,56,]),'USING':([42,],[58,]),'AND':([46,47,48,62,],[-32,-33,-34,76,]),'SEQ':([54,64,],[66,66,]),'BTREE':([54,64,],[67,67,]),'RTREE':([54,64,],[68,68,]),'AVL':([54,64,],[69,69,]),'ISAM':([54,64,],[70,70,]),'HASH':([54,64,],[71,71,]),'RBRACKET':([72,73,],[79,80,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'sentencia':([0,],[2,]),'columns':([4,15,],[8,21,]),'def_columnas':([18,41,],[25,57,]),'columna':([18,41,],[26,26,]),'condicion_where':([20,],[28,]),'condicion':([23,29,],[32,43,]),'tipo':([24,],[33,]),'valores':([30,60,],[44,75,]),'valor':([30,49,50,60,63,76,83,],[45,61,62,45,77,82,85,]),'opciones_col':([33,],[52,]),'tipo_indice':([54,64,],[65,78,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> sentencia','programa',1,'p_programa','parser.py',88),
  ('sentencia -> CREATE TABLE ID LPAREN def_columnas RPAREN','sentencia',6,'p_sentencia_create_def','parser.py',93),
  ('def_columnas -> columna','def_columnas',1,'p_def_columnas','parser.py',97),
  ('def_columnas -> columna COMMA def_columnas','def_columnas',3,'p_def_columnas','parser.py',98),
  ('columna -> ID tipo opciones_col','columna',3,'p_columna','parser.py',105),
  ('tipo -> INT','tipo',1,'p_tipo','parser.py',109),
  ('tipo -> VARCHAR LBRACKET NUM RBRACKET','tipo',4,'p_tipo','parser.py',110),
  ('tipo -> DATE','tipo',1,'p_tipo','parser.py',111),
  ('tipo -> ARRAY LBRACKET FLOAT RBRACKET','tipo',4,'p_tipo','parser.py',112),
  ('tipo -> TEXT','tipo',1,'p_tipo','parser.py',113),
  ('tipo -> FLOAT','tipo',1,'p_tipo','parser.py',114),
  ('opciones_col -> <empty>','opciones_col',0,'p_opciones_col','parser.py',123),
  ('opciones_col -> KEY','opciones_col',1,'p_opciones_col','parser.py',124),
  ('opciones_col -> KEY INDEX tipo_indice','opciones_col',3,'p_opciones_col','parser.py',125),
  ('opciones_col -> INDEX tipo_indice','opciones_col',2,'p_opciones_col','parser.py',126),
  ('tipo_indice -> SEQ','tipo_indice',1,'p_tipo_indice','parser.py',138),
  ('tipo_indice -> BTREE','tipo_indice',1,'p_tipo_indice','parser.py',139),
  ('tipo_indice -> RTREE','tipo_indice',1,'p_tipo_indice','parser.py',140),
  ('tipo_indice -> AVL','tipo_indice',1,'p_tipo_indice','parser.py',141),
  ('tipo_indice -> ISAM','tipo_indice',1,'p_tipo_indice','parser.py',142),
  ('tipo_indice -> HASH','tipo_indice',1,'p_tipo_indice','parser.py',143),
  ('sentencia -> CREATE TABLE ID FROM FILE CADENA USING INDEX ID LPAREN CADENA RPAREN','sentencia',12,'p_sentencia_create_file','parser.py',148),
  ('sentencia -> SELECT columns FROM ID condicion_where','sentencia',5,'p_sentencia_select','parser.py',153),
  ('columns -> ASTERISCO','columns',1,'p_columns','parser.py',157),
  ('columns -> ID','columns',1,'p_columns','parser.py',158),
  ('columns -> ID COMMA columns','columns',3,'p_columns','parser.py',159),
  ('condicion_where -> <empty>','condicion_where',0,'p_condicion_where','parser.py',169),
  ('condicion_where -> WHERE condicion','condicion_where',2,'p_condicion_where','parser.py',170),
  ('condicion -> ID EQUAL valor','condicion',3,'p_condicion','parser.py',174),
  ('condicion -> ID BETWEEN valor AND valor','condicion',5,'p_condicion','parser.py',175),
  ('condicion -> ID IN LPAREN valor COMMA valor RPAREN','condicion',7,'p_condicion','parser.py',176),
  ('valor -> NUM','valor',1,'p_valor','parser.py',185),
  ('valor -> FLOATVAL','valor',1,'p_valor','parser.py',186),
  ('valor -> CADENA','valor',1,'p_valor','parser.py',187),
  ('sentencia -> INSERT INTO ID VALUES LPAREN valores RPAREN','sentencia',7,'p_sentencia_insert','parser.py',193),
  ('valores -> valor','valores',1,'p_valores','parser.py',197),
  ('valores -> valor COMMA valores','valores',3,'p_valores','parser.py',198),
  ('sentencia -> DELETE FROM ID WHERE condicion','sentencia',5,'p_sentencia_delete','parser.py',207),
]
